### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by Ilesh** [developermypos/myPOS-SDK-iOS#2]
I am working with **Xcode 11.1** and the latest **swift version**. I able to add myPOSBluetoothSDK via TARGETS --> General --> Frameworks, Libraries, and Embedded Content and Also import in the bridging header file then compile it works.

But the issue is when I used any of the methods or lines in the code it shows me the below error.

**Line of code :** 
`myPOSService.setAppName("myApp Name")
`
**Error:**

```
ld: warning: ignoring file xxxx....project path/myPOSBluetoothSDK.framework/myPOSBluetoothSDK, missing required architecture x86_64 in file xxxx....project path/myPOSBluetoothSDK.framework/myPOSBluetoothSDK (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_myPOSService", referenced from:
      objc-class-ref in OrderDetailsVC.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Please help me to solve this issue as soon as possible. 

Thank you in advance.
